// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfvydxnrefohnxwdlaxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmdnlkeG5yZWZvaG54d2RsYXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTY0OTIsImV4cCI6MjA2ODU3MjQ5Mn0.I5OGITJ-XTF0evhGmwt8bxmmrCSM6hLQYHmVOqqQ-Kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});